### ISSUE TITLE
if (self.model == nil) 的oc为空判断，oc nil 转为lua nil

### ISSUE THREAD

**Issue by RamboQiu** [hzfanfei/spa#1]

**Comment by ChenMengqi** [comment]
原来的 `+ (int)toLuaObject:(lua_State *)L object:(id)object`
方法里将 oc 里的 nil 转为了 userdata，这里直接改成 lua nil ，已提交至dev

**Comment by ChenMengqi** [comment]
为了保证lua中对nil发送方法不crash，所以 oc nil 不能直接转为 lua nil，因此 额外封装 isNull方法来判断 userdata是否为空，使用方式为 spa.isNull()
