### ISSUE TITLE
OC方法中，如果有参数且先CGPoint后BOOL值，会crash

### ISSUE THREAD

**Issue by ChenMengqi** [hzfanfei/spa#4]
报错信息为：[SPA] PANIC: unprotected error in call to Lua API (attempt to index a boolean value)

如常见方法 `[self.tableView setContentOffset:xxx animated:YES];`

**Comment by ChenMengqi** [comment]
![test](https://user-images.githubusercontent.com/9972678/89146094-4a2c3800-d585-11ea-9f5b-5b7b42dc1bcb.png)

![test2](https://user-images.githubusercontent.com/9972678/89146124-616b2580-d585-11ea-92b5-75fb8dc3e75c.png)


这段代码中的 取栈逻辑有错，待修改

**Comment by hzfanfei** [comment]
to struct 没有使用index索引table
