### ISSUE TITLE
调用的oc方法里面，有一个带参数的block，block里的参数最后获取不到

### ISSUE THREAD

**Issue by RamboQiu** [hzfanfei/spa#5]
oc:
- (void)doSomeThing {
    
}

- (void)doSomeThing:(void(^)(int i))block {
    block(5);
}

spa:
function doSomeThing(self)
  local block = function(i)
    spa.log(i)
  end
  
  self:doSomeThing_(block)
  
end

--------------------------
这个参数i 是null，获取不到，用type(i) 读出来的也是nil

**Comment by hzfanfei** [comment]
// 使用问题，正确的例子如下，要用block函数来显示构造function，告知签名

spa_class("ViewController")

function doSomeThing(self)

self:doSomeBlock_(block(function(i) spa.log(i) end, 'v', {'i'}))

end
