### ISSUE TITLE
有偶现的 无法调用到 oc类的情况

### ISSUE THREAD

**Issue by ChenMengqi** [hzfanfei/spa#8]
可以确认的是 oc本身是可以调用到的， 不为空，但lua调用存在 偶现找不到方法的情况，原因未知，排查中。

报错信息为：
`[SPA] PANIC: unprotected error in call to Lua API ([string "spa_class("xxxx")..."]:8: attempt to index a nil value)`

**Comment by ChenMengqi** [comment]
此时 lua中获取到的self 为空

初步排查后，原因在 前后两次 类的实例 地址相同，导致 

```
+ (int)createInstanceUserData:(lua_State *)L object:(id)object {
       ......
        lua_pushlightuserdata(L, (__bridge void *)(object));
       if(lua_isnil(L, -1) ){
       } else {
     }
```
走到了`else`逻辑，最后导致self为空

**Comment by hzfanfei** [comment]
lua_isnil(L, -1) 只判断空是不够的的，还要判断内部的instance是否为空
